
[[toolchains]]
name          = "nightly-2021-11-05"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (4961b107f 2021-11-04)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-06"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (0d1754e8b 2021-11-05)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-07"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (072799443 2021-11-06)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-08"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (46b8e7488 2021-11-07)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"

[[toolchains]]
name          = "nightly-2021-11-09"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (495322d77 2021-11-08)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"

[[toolchains]]
name          = "nightly-2021-11-10"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (8b09ba6a5 2021-11-09)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"

[[toolchains]]
name          = "nightly-2021-11-11"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (82af160c2 2021-11-10)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-12"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (936238a92 2021-11-11)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-13"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (e90c5fbbc 2021-11-12)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-14"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (b416e3892 2021-11-13)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-15"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (ad4423997 2021-11-14)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-16"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (891ca5f63 2021-11-15)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-17"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (d914f17ca 2021-11-16)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-18"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (c9c4b5d72 2021-11-17)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-19"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (cc946fcd3 2021-11-18)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-20"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (a77da2d45 2021-11-19)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-21"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (2885c4748 2021-11-20)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-22"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (65f3f8b22 2021-11-21)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-23"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (936f2600b 2021-11-22)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-24"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (65c55bf93 2021-11-23)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-25"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (b426445c6 2021-11-24)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-26"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (dd549dcab 2021-11-25)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-27"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (6d246f0c8 2021-11-26)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-28"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (686e313a9 2021-11-27)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-29"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (db9d361a4 2021-11-28)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-30"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (6db0a0e9a 2021-11-29)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-01"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (207c80f10 2021-11-30)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-02"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (48a5999fc 2021-12-01)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-03"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (acbe4443c 2021-12-02)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-04"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (532d2b14c 2021-12-03)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-05"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (efec54529 2021-12-04)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-06"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (e2116acae 2021-12-05)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-07"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (0fb1c371d 2021-12-06)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-08"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (0b6f079e4 2021-12-07)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-09"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (e6b883c74 2021-12-08)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-12-10"
type          = "ok"
rustc_version = "rustc 1.59.0-nightly (0b42deacc 2021-12-09)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"

[[toolchains]]
name          = "nightly-2021-12-11"
type          = "missing"
