
[[toolchains]]
name          = "nightly-2021-11-05"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (4961b107f 2021-11-04)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-06"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (0d1754e8b 2021-11-05)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-07"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (072799443 2021-11-06)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "ok"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "ok"

[[toolchains]]
name          = "nightly-2021-11-08"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (46b8e7488 2021-11-07)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"

[[toolchains]]
name          = "nightly-2021-11-09"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (495322d77 2021-11-08)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"

[[toolchains]]
name          = "nightly-2021-11-10"
type          = "ok"
rustc_version = "rustc 1.58.0-nightly (8b09ba6a5 2021-11-09)"

[[toolchains.targets]]
name          = "aarch64-kmc-solid_asp3"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabi"
type          = "error"

[[toolchains.targets]]
name          = "armv7a-kmc-solid_asp3-eabihf"
type          = "error"
